language: java
jdk:
- oraclejdk9
script: mvn clean install  sonar:sonar
deploy:
  provider: bintray
  file: ".bintray.json"
  user: "sandor-nemeth"
  key:
    secure: rt8Yv6F7oja25dxA4QKSeaJbJiNdLhuVdcZlM1BRuZxipODjI2bHSyfg0XQ5PCyrjn5EIiesEU6oGOdu67D/KDUNVEE58vPtmIE5PT4y83kzv5dS1pEZuYjA6xEXJCddOmOGuATsCYT0g/E8t7GDoKd3J56Kc6kX+Kc2qEG9CPOjBUjyKuRPyRIso+1abJ7dxywmrlrg+VoFLPa7eO49zeKL6dWSh7sta/0JLOWBlrHl0JefNokG08qbZDhpr3bukdiPzotVrnpBDbvyfoVqhM8Xb1QBb24CGtpGdRh+gCaQ5oExf5P0EJNcle9K0dzloJnk9/eF7FGlrDQPH97hUikcViJxY8UmIJijWhYsmN6fy5Xig0t63+DWUOXwWoUvyxIY5prrLb/oAbZ7XeLLYPKndlu5sPwOYUHXgovUVwYMs3MO2ewfaBeMnNo/YYZhDrA3tJuBjmK5ofl5PI4fTulPj/m5bMBXKV1mR2UNpeqKzyVOi6OppaHn/tsuxq51L5BEiaXxOESBpVfRAg62wqfp8MNEtlnydijV9Qbro+M3VezD/XE5jenGvc76bkBJ+xKTfTLgePbGiHO2sXFaH6njXRL66Sr5gkg7j367xAJK6HdF6OphH+LLu68uMefzoI/Jx/6rdP3C/FIbCGthyk3o1HeTPDMifzUVG2IhDUc=
  dry-run: false
  on:
    repo: jux-router/jux
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN=5c618ddc-f969-41eb-8174-da55e6450c53
addons:
  sonarcloud:
    organization: "jux-router"
    token:
      secure: "TcQQ5CGoZuJDxREFao956yVDANXfF2USMCrU5gN7acbMk4b2J4pahpSyhKtRwb4Tdz3AVgONEgOJWGcuzIo7aVS8GmiL6Fh7gHt/l9NG63BsLwybszvgaxkgUu+4d78V3W+JLipikLZrLstZ5D6Awvww+EHW2/boeRdB2+R10j8wUitgWPftBqqP6cxl5yZQ+rWV7nJTmJSBs8uCzcOEvxhpcxSopK0BIYZTwNBsavXmttHbcNXX4NW+a0zi31IF0fUaPVHenAce9heNJ6heC/p4RBNgtfr7k3qLRpswJSD68nD5aoNHeQ96TQnnO92gXijZMyR03+nCd2x7TV42QfI/AQGjX7Zu6DtPCZui0NOGkIOi4Fzd2JYehJcR3JkD+Ed1ksld4uezRBlDCHM+qlzkrP6wlKjZ4gAle6B2uv1MaHUA3RlsE5AKQpWmyNw3KFZOHajsnRSr0aoD1nARsZFhS+y7Gn7NvwIRIxWJYhwRu9KO+pCRTkLXDTYMFIAWBZsy0xsvenuwp4XRGVazRzz9ArIPuDwVGngqX9poH5bcQn2DtIiGYIuTsIqmsBuLaX+883zLDm27mIb3hlKnlB/t5HpuNULY2+Y46/8RPCVbg14CfpvYqfGfYHALEcr3it+g11EQYtfH3lndXHT7LRuTtAgAMTtJis9wtZK8IWY="
