language: java
sudo: false
install: true

jdk:
- oraclejdk9

script: mvn clean package

deploy:
  provider: bintray
  file: ".bintray.json"
  user: "sandor-nemeth"
  key:
    secure: rt8Yv6F7oja25dxA4QKSeaJbJiNdLhuVdcZlM1BRuZxipODjI2bHSyfg0XQ5PCyrjn5EIiesEU6oGOdu67D/KDUNVEE58vPtmIE5PT4y83kzv5dS1pEZuYjA6xEXJCddOmOGuATsCYT0g/E8t7GDoKd3J56Kc6kX+Kc2qEG9CPOjBUjyKuRPyRIso+1abJ7dxywmrlrg+VoFLPa7eO49zeKL6dWSh7sta/0JLOWBlrHl0JefNokG08qbZDhpr3bukdiPzotVrnpBDbvyfoVqhM8Xb1QBb24CGtpGdRh+gCaQ5oExf5P0EJNcle9K0dzloJnk9/eF7FGlrDQPH97hUikcViJxY8UmIJijWhYsmN6fy5Xig0t63+DWUOXwWoUvyxIY5prrLb/oAbZ7XeLLYPKndlu5sPwOYUHXgovUVwYMs3MO2ewfaBeMnNo/YYZhDrA3tJuBjmK5ofl5PI4fTulPj/m5bMBXKV1mR2UNpeqKzyVOi6OppaHn/tsuxq51L5BEiaXxOESBpVfRAg62wqfp8MNEtlnydijV9Qbro+M3VezD/XE5jenGvc76bkBJ+xKTfTLgePbGiHO2sXFaH6njXRL66Sr5gkg7j367xAJK6HdF6OphH+LLu68uMefzoI/Jx/6rdP3C/FIbCGthyk3o1HeTPDMifzUVG2IhDUc=
  dry-run: false
  on:
    repo: jux-router/jux
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN=5c618ddc-f969-41eb-8174-da55e6450c53

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
